typography_spectrum: 0.8116319803521037
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.3042203220538795
  saturation: 0.8043639895040542
  rhythmicContrast: 0.6280327343847603
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50879
analytics:
  google: null
  facebook: null
  twitter: null
name: zeitwurst
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This is Zeitwurst
description: Word sausages composed of timely digits
purpose: []
